/**
 * 📅 Calendar Controller
 * 
 * Handles all CRUD logic for CalendarEvent.
 * 
 * ⚠️ date must be epoch midnight (00:00 UTC) sent by Client.
 * UNIQUE constraint per userId + date → 1 outfit per day per user.
 * Uses upsert to REPLACE if an event already exists for that day.
 */
const CalendarEvent = require('../models/CalendarEvent');
const Outfit = require('../models/Outfit');
const ClothingItem = require('../models/ClothingItem');
const asyncHandler = require('../middleware/asyncHandler');
const { AppError } = require('../middleware/errorHandler');

/**
 * 📋 GET /api/calendar
 * 
 * Get list of calendar events.
 * Supports query params:
 *   - date: Get event for a specific day (epoch midnight)
 *   - from, to: Get events for a date range
 *   - populate: if "true" → also return outfit + clothing item details
 *
 * If no params, returns all events.
 * 
 * Response: { success: true, count: Number, data: [...] }
 */
const getCalendarEvents = asyncHandler(async (req, res) => {
  const { date, from, to, populate } = req.query;
  const currentUserId = req.user._id;

  let filter = { userId: currentUserId };

  if (date) {
    const dateNum = Number(date);
    if (isNaN(dateNum)) {
      return res.status(400).json({
        success: false,
        message: 'Date parameter must be a number (epoch millis)'
      });
    }
    filter.date = dateNum;
  } else if (from && to) {
    const fromNum = Number(from);
    const toNum = Number(to);
    if (isNaN(fromNum) || isNaN(toNum)) {
      return res.status(400).json({
        success: false,
        message: 'From and to parameters must be numbers (epoch millis)'
      });
    }
    filter.date = { $gte: fromNum, $lte: toNum };
  }

  let events = await CalendarEvent.find(filter).sort({ date: 1 });

  if (populate === 'true' && events.length > 0) {
    const outfitIds = [...new Set(events.map(e => e.outfitId))];
    const outfits = await Outfit.find({ _id: { $in: outfitIds } }).lean();
    const allItemIds = [
      ...new Set(outfits.flatMap(o => o.clothingItems.map(ci => ci.clothingItemId)))
    ];
    const clothingItems = await ClothingItem.find({ _id: { $in: allItemIds } }).lean();
    const clothingMap = {};
    clothingItems.forEach(item => { clothingMap[item._id] = item; });
    const outfitMap = {};
    outfits.forEach(o => {
      o.clothingItems = o.clothingItems.map(ci => ({
        ...ci,
        clothingItem: clothingMap[ci.clothingItemId] || null
      }));
      outfitMap[o._id] = o;
    });
    events = events.map(event => ({
      ...event.toObject(),
      outfit: outfitMap[event.outfitId] || null
    }));
  }
  res.status(200).json({
    success: true,
    count: events.length,
    data: events
  });
});

/**
 * 🔍 GET /api/calendar/:id
 */
const getCalendarEventById = asyncHandler(async (req, res, next) => {
  const { id } = req.params;
  const currentUserId = req.user._id;
  const event = await CalendarEvent.findOne({ _id: id, userId: currentUserId });
  if (!event) {
    return next(new AppError(`CalendarEvent not found with ID: ${id}`, 404));
  }
  res.status(200).json({ success: true, data: event });
});

/**
 * ➕ POST /api/calendar
 *
 * Assign (or replace) an Outfit to a day.
 *
 * ⚠️ Uses findOneAndUpdate with upsert=true to avoid E11000 duplicate key error.
 * Old index { date: 1 } (unique) may still exist in DB, upsert will bypass.
 *
 * Body:
 *   - _id: String (UUID generated by Client)
 *   - date: Number (epoch midnight)
 *   - outfitId: String (Outfit UUID)
 */
const createOrReplaceCalendarEvent = asyncHandler(async (req, res) => {
  const { _id, date, outfitId } = req.body;
  const currentUserId = req.user._id;

  // Validation
  if (!_id) {
    return res.status(400).json({ success: false, message: '_id (UUID) field is required' });
  }
  if (date === undefined || date === null) {
    return res.status(400).json({ success: false, message: 'date (epoch midnight) field is required' });
  }
  if (!outfitId) {
    return res.status(400).json({ success: false, message: 'outfitId field is required' });
  }

  const dateNum = Number(date);
  if (isNaN(dateNum)) {
    return res.status(400).json({ success: false, message: 'date must be a number (epoch millis)' });
  }

  const ownedOutfit = await Outfit.findOne({ _id: outfitId, userId: currentUserId });
  if (!ownedOutfit) {
    return res.status(404).json({
      success: false,
      message: 'Outfit does not exist or does not belong to the user'
    });
  }

  // ⚡ UPSERT: find by userId+date → if not exists create, if exists update outfitId
  // Use upsert instead of find + create to avoid E11000 duplicate key (old date_1 index)
  // IMPORTANT: Do not $set _id because _id is immutable once created
  const updatedEvent = await CalendarEvent.findOneAndUpdate(
    { userId: currentUserId, date: dateNum },
    { $set: { outfitId }, $setOnInsert: { _id } },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  );

  res.status(200).json({
    success: true,
    message: 'Outfit assigned successfully',
    data: updatedEvent
  });
});

/**
 * ✏️ PUT /api/calendar/:id
 */
const updateCalendarEvent = asyncHandler(async (req, res, next) => {
  const { id } = req.params;
  const { outfitId, date } = req.body;
  const currentUserId = req.user._id;

  const updateData = {};
  if (outfitId !== undefined) updateData.outfitId = outfitId;
  if (date !== undefined) {
    const dateNum = Number(date);
    if (isNaN(dateNum)) {
    return res.status(400).json({ success: false, message: 'date must be a number (epoch millis)' });
    }
    updateData.date = dateNum;
  }

  const updatedEvent = await CalendarEvent.findOneAndUpdate(
    { _id: id, userId: currentUserId },
    updateData,
    { new: true, runValidators: true }
  );

  if (!updatedEvent) {
    return next(new AppError(`CalendarEvent not found with ID: ${id}`, 404));
  }
  res.status(200).json({ success: true, data: updatedEvent });
});

/**
 * ❌ DELETE /api/calendar/:id
 */
const deleteCalendarEvent = asyncHandler(async (req, res, next) => {
  const { id } = req.params;
  const currentUserId = req.user._id;
  const deletedEvent = await CalendarEvent.findOneAndDelete({ _id: id, userId: currentUserId });
  if (!deletedEvent) {
    return next(new AppError(`CalendarEvent not found with ID: ${id}`, 404));
  }
  res.status(200).json({ success: true, message: `CalendarEvent deleted: ${id}`, data: {} });
});

/**
 * ❌ DELETE /api/calendar/by-date/:date
 */
const deleteCalendarEventByDate = asyncHandler(async (req, res, next) => {
  const { date } = req.params;
  const currentUserId = req.user._id;
  const dateNum = Number(date);
  if (isNaN(dateNum)) {
    return res.status(400).json({ success: false, message: 'date must be a number (epoch millis)' });
  }
  const deletedEvent = await CalendarEvent.findOneAndDelete({ userId: currentUserId, date: dateNum });
  if (!deletedEvent) {
    return next(new AppError(`Event not found for date: ${dateNum}`, 404));
  }
  res.status(200).json({ success: true, message: `Event deleted for date ${dateNum}`, data: deletedEvent });
});

/**
 * 🗑️ DELETE /api/calendar/bulk
 */
const bulkDeleteCalendarEvents = asyncHandler(async (req, res) => {
  const currentUserId = req.user._id;
  const result = await CalendarEvent.deleteMany({ userId: currentUserId });
  res.status(200).json({
    success: true,
    message: `Deleted ${result.deletedCount} calendar event(s)`,
    deletedCount: result.deletedCount
  });
});

module.exports = {
  getCalendarEvents,
  getCalendarEventById,
  createOrReplaceCalendarEvent,
  updateCalendarEvent,
  deleteCalendarEvent,
  deleteCalendarEventByDate,
  bulkDeleteCalendarEvents
};